{% set name = "Flask-SeaSurf" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxcountryman/flask-seasurf/archive/{{ version }}.tar.gz
  sha256: de84c7f1ae5bf16c39965ce7d73069c676cfea85dd9d0ec519bb729809a31732

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - flask

test:
  imports:
    - flask_seasurf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxcountryman/flask-seasurf/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An updated CSRF extension for Flask.
  doc_url: https://flask-seasurf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
