{% set name = "Flask-SeaSurf" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - flask

test:
  imports:
    - flask_seasurf

about:
  home: https://github.com/maxcountryman/flask-seasurf/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'An updated CSRF extension for Flask.'
  doc_url: https://flask-seasurf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
