{% set name = "Flask-SeaSurf" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxcountryman/flask-seasurf/archive/{{ version }}.tar.gz
  sha256: 86d5d98b7969fea96a7e9370af79f0096cf3bc6a99ca7e3ff592fe19ff0ab748

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - flask

test:
  imports:
    - flask_seasurf
  commands:
    - pip check
  requires: 
    - pip

about:
  home: https://github.com/maxcountryman/flask-seasurf/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'An updated CSRF extension for Flask.'
  doc_url: https://flask-seasurf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
