{% set name = "Flask-SeaSurf" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxcountryman/flask-seasurf/archive/{{ version }}.tar.gz
  sha256: a3af184f32190217704720628e3694ea533004d238b644fe96d0bc7bac5b2d62

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - flask

test:
  imports:
    - flask_seasurf

about:
  home: https://github.com/maxcountryman/flask-seasurf/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'An updated CSRF extension for Flask.'
  doc_url: https://flask-seasurf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
