travis:
  secure:
    BINSTAR_TOKEN: lhbcB9G8mQfbSw6ESUjwtrgmBXHZznY1oo7uto/wuSp2edUFvpXX0jJo1SK7Sw7wbOUgPxzJ1XGEbYqcJaSO32+MrtiTsF9KZ3cySOVuSWjCRCx/UnEkLwJUAj+1prrM3lGu6H5NUH/6woZw4kXrMja2o80MYAv6tk6T6VpLt1ZqddLQG36L4Cm2GyraVHH0Rn+9xmXuQVBFgw1P9ukU7LTxfrHEonlTDHWilDnMSioQYsgsJY6E2kccH8zBgPZlzyjoCOBKCEy4FVFIKNuCScqzfl1yPwd6J/9vYYAnD7q2M32viIwz+27Zd7Yv6RLpJnLKAnCni2gHkLopodsiDF6fmVA+J4NoZW+9h1+whLcruIVTHZtxc2wiAa8AFipOD0yg4NvytgVC6jyBingAGB9mlhWzrvxCdRj/cgjcSs5AIjUDpPy1n9fMdwZn4SJIcu/LldOuGDNneCy9gP5ygtyvXVxkzUducNH1jA7TBiPwyuy5gZRhmG3bKP4+UFMSKPQLzEmpjFvYQ4ZWkrdULvACpSHsSZpCC5cvnmMJ1jZfZ48zULvd1B73SQ0bwgR3d+jRpsjL+kCNlkr0nzfAOOSBGI4vdbuLX4J7uYXdCZlhPo00C/mTV+xc+ysc//tpi7cl6UqAi8YIyFfpcsgR32Hq3YlvOvDYjEuTIBxvXA4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
