travis:
  secure:
    BINSTAR_TOKEN: ntRV8QCP+KJL+hMoTvgvWvqhxWfsxVI8UqFHIr4F7Edcw65CxjXsPbA4XaCfR7QbDlWPQjbubUYwLRi8Ue7az3km7H9Q5IRDb/vHjhivv/F6c4CLOF1FPIK8yLZDflT0i1D4J7Zu7AO5KJJ4Xejviq0Td0mQIEPPqVAsDTVt8KATW+cF2fRf9F24voCkcnj8GTJmV3Q5DAh7xBuwQXWtMtEmQBs/TJfBn95fI6ZbgSxgYSobE8QaihVT9xfVB/rTcdPDUjbRmIKh6ZK7/ymoujJCdJQajtek+3j4T89HzLPCQJah6p2dcQn++E0L4hEtGynRzDvx+S0Or5a1TFSzSq23mCBE/iP+aEUdIuv5GVfG+KkdmZyNpCOEystbR6c/PeBG7UaJc+YeFyaSmuSxee4VaC+miTG9CbBNWwzuTWUOXHvyU+xRmeor1K0ctHAeBfZmNbGB7nlACN3xFDUXyN9am5dxu5wA5h9HHbFtH7BlC7/kkNalpbgvnpTt2+yfDffvpCPzDlld9hk40nbMpti8IX9ukXLsVHZ+clHD6L0XKxFEu1d0lNra8WTHSspm6aeDXV+vuWe+Mcy8F95Pk8xesEefw5blhCJR8j9FH9MPPjDzUKKP1JJSeRAg3SDDBEBsoktbR1FCyY56heuxRaSZ7QE0c045JszvjGK6aM0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
