appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dchhGNpJEW+1S4sK562ewDjfqO7D2Z3XxvBGIBtzwuMFAVnGIqeRerl9sHAH2jQNeob20hYo475bA1nmzf4oAZqYBSUUFZZ/AYj0N6SI+dyqxrsEVrfULGlvdmZyHETCyzk37cqDNiThMOheW+txCM5caHqp9JBgCL+HLrPC+Bs1c0hJ4NbVH1rUwtuLKoOq0I8gE1ki9AsHYdqiy92GpTEsz7QI33tzLbGeKhLcIvluB2k0rP5IKNILtQNZGxYtHcDJDmPuZ7N+2acuralB0Kj4PlTA45tel+O2574yCjeI2X7FkAu8/B9mAcIgaMiXY51m1yWlQvZa9VSS4ljkoI54cvEYY/N6Fjnp7aL1gYcmj/yYwuIiGHb9WqCAmM60vOnTp6ndKm/oHNmiOT60NUpBZystcHXvCDKXrcLKiOsoczLcYsfGVQfiEEAufnGb21G4Bc+IwEkfKeSdcx9aUIW634JtedOoPuufemdxIsuEFsrF1Q4D0ItVSCL41j1pxfUrVT6uGuO8NTvafPiWIrAuDjCH7r6WlFu6j4cELilQvNoWxI4TlqZznicO/JjECniKgbtMSuNcPPcJTZIB2Cz9ZaKbrjAiN8ItZq3fHKU22ZmoshSycYRNDtIXx0ng+4p4yhxS2vfSrLTPu34uTmINPEO1l4Rlr8uhbSZRtDU=}
