travis:
  secure:
    BINSTAR_TOKEN: FdsUFQosL6Ufd96y63YFm59h+Sc8CVbP9PsKIUj1nUP54ZYiWgJc6tcscWOzii/7yaNjxvp21Y59OTACC8fNRBSoTxCK2oTIruv5ipIJ1s5tgKRLXAg13ySFiFegwpKpsHGwghDNj6Z2k4wC7Sd5Bdh+53x6f4TxsjcYLBizgQZgrolGgTG5yi1bHXY1M8pjeSSubKj1eAu1vNdlXq1Tv+eyJZoBpzJZVQ/molJKhlIt0nOXrvVoJTquQ7aVuQx/vGFBuDXi/uAxBq6rJK5w+vMt6Ea+HDj8bWBXVMvT9INyUvJYLQ0Bq6fq0qlWQEiGIHInVlVAY9yqrQMAveoA3sY1c8mgjwfVcpVqeQvaak4mPWtOAewpxO158zRrS8MQtimj8DY5Pobb+MPW74Vr42azV5iIaRey2+J07znP46ENfj5q1LF5M2LAEQBAvLcJ8AP7S/zhMKDmwuFmm8wnwTqV/RotuJ/j4UBpuzbZOz5zNCA8m2iUuwA2hcnIfK2lRx6UCs7y2g70dLu0VJKoeQtksgBY8QCEU91qkTec/BhzK/yOFmM3xWR5qQhpYJM6DYqfKY2AaYPYBoDk6QkgRpJ33BUXjHGqsVKcp135faAsXUTb/Oz1L4gEEVxGnnYRCuwukRqjfQDWfa4UotlYmj/BXSfgBpXbe5Acr9v+mPE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
